# Generated by Django 3.0.7 on 2020-10-20 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'views',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lastname', models.BooleanField(db_index=True, default=True)),
                ('is_phone', models.BooleanField(db_index=True, default=True)),
                ('is_city', models.BooleanField(db_index=True, default=True)),
                ('is_import', models.BooleanField(db_index=True, default=True)),
                ('is_origin', models.BooleanField(db_index=True, default=True)),
                ('is_code', models.BooleanField(db_index=True, default=True)),
                ('is_guest', models.BooleanField(db_index=True, default=True)),
                ('is_cancelation', models.BooleanField(db_index=True, default=True)),
                ('is_observation', models.BooleanField(db_index=True, default=True)),
                ('is_pay', models.BooleanField(db_index=True, default=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('cash', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Payments',
                'managed': True,
            },
        ),
    ]
