# Generated by Django 3.0.7 on 2020-10-26 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='auth',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='birthdate',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.PositiveIntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='settings_forms',
            name='is_birthdate',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
