# Generated by Django 3.0.7 on 2020-10-22 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('lastname', models.CharField(max_length=1024, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dni', models.CharField(max_length=1024, null=True)),
                ('phone', models.PositiveIntegerField(max_length=1024, null=True)),
                ('street', models.CharField(max_length=1024, null=True)),
                ('city', models.CharField(max_length=1024, null=True)),
                ('country', models.CharField(max_length=1024, null=True)),
                ('cp', models.CharField(max_length=1024, null=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(unique=True)),
                ('end_time', models.DateTimeField()),
                ('guest', models.PositiveIntegerField(max_length=1024, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='owner.Client', unique=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telapi.Flat', unique=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
