# Generated by Django 3.0.7 on 2020-10-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_client_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservation',
        ),
    ]
