# Generated by Django 3.0.7 on 2020-10-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20201026_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthdate',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest',
            field=models.PositiveIntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='settings_forms',
            name='is_birthdate',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
