# Generated by Django 3.0.7 on 2020-10-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20201020_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='is_cancelation',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_city',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_code',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_guest',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_import',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_lastname',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_observation',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_origin',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_pay',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_phone',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
