# Generated by Django 3.0.7 on 2020-10-20 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0003_auto_20201020_2008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Settings_forms',
        ),
        migrations.AlterModelTable(
            name='settings_forms',
            table='settings_forms',
        ),
        migrations.CreateModel(
            name='Settings_alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_temperature', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('min_temperature', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('start_time', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('end_time', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('max_capacity', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('listening_time', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_alerts',
                'managed': True,
            },
        ),
    ]
