# Generated by Django 3.0.7 on 2020-10-22 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20201022_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='street',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='tlf',
        ),
        migrations.AddField(
            model_name='client',
            name='birthdate',
            field=models.DateTimeField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
