# Generated by Django 3.0.7 on 2020-10-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_auto_20201022_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='owner_user',
        ),
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateTimeField(null=True, unique=True),
        ),
    ]
