# Generated by Django 3.0.7 on 2020-10-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat_owner_access',
            name='date_access_end',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='flat_owner_access',
            name='date_access_start',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
    ]
