# Generated by Django 3.0.7 on 2020-10-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('telapi', '0001_initial'),
    ]

    operations = [
    ]
