# Generated by Django 3.0.7 on 2020-10-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='telapi.OwnersData'),
            preserve_default=False,
        ),
    ]
