# Generated by Django 3.0.7 on 2020-10-26 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat_Owner_Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_access', models.CharField(db_index=True, max_length=255)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telapi.Flat')),
            ],
            options={
                'db_table': 'flat_owner_access',
                'managed': True,
            },
        ),
    ]
