# Generated by Django 3.0.7 on 2020-10-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='flat',
            name='ocupied',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
