# Generated by Django 3.0.7 on 2020-10-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0002_flat_owner_access'),
        ('telapi', '0002_auto_20201026_1304'),
    ]

    operations = [
    ]
