# Generated by Django 3.0.7 on 2020-10-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        ('telapi', '0002_auto_20201021_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners_data',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='superadmin.OwnersData'),
            preserve_default=False,
        )
    ]
