# Generated by Django 3.0.7 on 2020-10-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0003_auto_20201021_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='reference',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
