# Generated by Django 3.0.7 on 2020-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0004_auto_20200711_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='recieved',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='iot_user_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
