# Generated by Django 3.0.7 on 2020-07-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0005_auto_20200711_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
