# Generated by Django 3.0.7 on 2020-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0006_grant_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='access_code',
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
