# Generated by Django 3.0.7 on 2020-07-16 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0007_auto_20200715_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=50, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telapi.Grant')),
            ],
        ),
    ]
