# Generated by Django 3.0.7 on 2020-07-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0008_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
    ]
