# Generated by Django 3.0.7 on 2020-07-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0009_auto_20200716_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='token',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
