# Generated by Django 3.0.7 on 2020-07-16 17:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('telapi', '0010_auto_20200716_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('grant_id', models.IntegerField()),
                ('access_id', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='instruction',
            name='grant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='telapi.Grant'),
            preserve_default=False,
        ),
    ]
