# Generated by Django 3.0.7 on 2020-08-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0011_auto_20200716_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('door', models.CharField(db_index=True, max_length=255, null=True)),
                ('city', models.CharField(db_index=True, max_length=255, null=True)),
                ('postal_code', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('value', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
            ],
        ),
    ]
