# Generated by Django 3.0.7 on 2020-08-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0012_flat_sensordata_sensortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
