# Generated by Django 3.0.7 on 2020-08-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0013_sensordata_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='iot_user_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
