# Generated by Django 3.0.7 on 2020-08-17 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telapi', '0014_auto_20200817_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='iot_user_id',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='iot_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
