# Generated by Django 3.0.7 on 2020-10-09 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telapi', '0015_auto_20200817_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telapi.Flat')),
                ('owner_user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('flat_id', 'owner_user_id')},
            },
        ),
    ]
