# Generated by Django 3.0.7 on 2020-09-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0016_flatowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatowner',
            name='iot_user_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
