# Generated by Django 3.0.7 on 2020-10-09 08:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telapi', '0016_flatowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatowner',
            old_name='flat_id',
            new_name='flat',
        ),
        migrations.RenameField(
            model_name='flatowner',
            old_name='owner_user_id',
            new_name='owner_user',
        ),
        migrations.AlterUniqueTogether(
            name='flatowner',
            unique_together={('flat', 'owner_user')},
        ),
    ]
