# Generated by Django 3.0.7 on 2020-10-09 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0017_auto_20201009_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatowner',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
