# Generated by Django 3.0.7 on 2020-10-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telapi', '0018_flatowner_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flatowner',
            unique_together=set(),
        ),
    ]
