# Generated by Django 3.0.7 on 2020-10-21 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnersData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=255, null=True)),
                ('last_name', models.CharField(db_index=True, max_length=255, null=True)),
                ('dni', models.CharField(db_index=True, max_length=255, null=True)),
                ('denomination', models.CharField(db_index=True, max_length=255, null=True)),
                ('manager', models.CharField(db_index=True, max_length=255, null=True)),
                ('cif', models.CharField(db_index=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('floor', models.PositiveIntegerField(blank=True, null=True)),
                ('door', models.CharField(db_index=True, max_length=255, null=True)),
                ('city', models.CharField(db_index=True, max_length=255, null=True)),
                ('postal_code', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owners_data',
                'managed': True,
            },
        ),
    ]
