# Generated by Django 3.0.7 on 2020-10-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownersdata',
            old_name='flat',
            new_name='flat_id',
        ),
        migrations.RenameField(
            model_name='ownersdata',
            old_name='iot_user',
            new_name='iot_user_id',
        ),
    ]
