# Generated by Django 3.0.7 on 2020-10-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_auto_20201021_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownersdata',
            old_name='iot_user_id',
            new_name='owner_user_id',
        ),
    ]
