# Generated by Django 3.0.7 on 2020-10-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_auto_20201021_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownersdata',
            old_name='flat_id',
            new_name='flat',
        ),
        migrations.RenameField(
            model_name='ownersdata',
            old_name='owner_user_id',
            new_name='owner_user',
        ),
    ]
