# Generated by Django 3.0.7 on 2020-10-21 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_auto_20201021_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatdata',
            name='owners_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='superadmin.OwnersData'),
        ),
    ]
