# Generated by Django 3.0.7 on 2020-10-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_auto_20201021_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownersdata',
            name='address',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='ownersdata',
            name='city',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ownersdata',
            name='door',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ownersdata',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownersdata',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
