# Generated by Django 3.0.7 on 2020-10-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_auto_20201021_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownersdata',
            name='dni',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ownersdata',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
